### ISSUE TITLE
数据库格式应该是什么样的呢？

### ISSUE THREAD

**Issue by xiaodaxiayuan** [heming6666/weapp-phonebook#2]
数据库格式应该是什么样的呢？

**Comment by heming6666** [comment]
**user** :
- categoryId 
- name 
- phone
- introduce 

**category**:
- categoryId
- name

类型都是string

**Comment by xiaodaxiayuan** [comment]
> **user** :
> 
> * categoryId
> * name
> * phone
> * introduce
> 
> **category**:
> 
> * categoryId
> * name
> 
> 类型都是string

我理解也是这样，权限管理也设置的所有用户可读，分类也能正常显示，甚至搜索能正常显示结果，但是进入页面是一条记录都不显示，很惊讶，不知道问题出在哪里

**Comment by heming6666** [comment]
你可以在 `miniprogram/pages/index/index.js` 的 **获取全部用户** 代码处打印一下返回的结果，如：
```
//获取全部用户
      wx.cloud.callFunction({
        name: 'getuserlist',
        data: {
          categoryId: 0
        },
        success(res) {
          that.setData({
            users: res.result.data
          })
          // 打印返回结果
          console.log(res)
        }
      })
```

**Comment by xiaodaxiayuan** [comment]
> 你可以在 `miniprogram/pages/index/index.js` 的 **获取全部用户** 代码处打印一下返回的结果，如：
> 
> ```
> //获取全部用户
>       wx.cloud.callFunction({
>         name: 'getuserlist',
>         data: {
>           categoryId: 0
>         },
>         success(res) {
>           that.setData({
>             users: res.result.data
>           })
>           // 打印返回结果
>           console.log(res)
>         }
>       })
> ```

返回的结果是空的，但是数据库里数据是正常的

**Comment by heming6666** [comment]
如果你拉取的是最新的代码的话，获取所有用户的代码 和 获取分类用户的代码 都是在云函数getuserlist里面的，能分类显示说明云函数的调用应该是没问题。你可以到云开发控制台的云函数模块里面查看到每一次的云函数调用情况。
另外，方便的话可以贴下console控制台显示的信息和其他具体情况。
